### ISSUE TITLE
Page doesnt load on GH-Pages

### ISSUE THREAD

**Issue by Nicholas-Arthur-Cook** [rtivital/react-pages-boilerplate#8]
Hi! Thanks for this boilerplate, this was working for one of my sites for a while and then randomly stopped.

It now loads as just a blank white page on the github site. When I run it on my local machine, it works just fine, but it doesn't work on the actual github pages site.

Any clues as to what could have changed that caused this?

**Comment by rtivital** [comment]
Hi, can you provide link to gh-pages?

**Comment by Nicholas-Arthur-Cook** [comment]
Yes of course! Thanks for the speedy response :)
its https://threshold-poem.github.io/

**Comment by rtivital** [comment]
The problem is [on this line](https://github.com/threshold-poem/threshold-poem.github.io/blob/master/settings.js#L12). Since you are using your profile Github domain it should be `repoPath: '/'`. 

This string should include repository name, for example, for repo https://github.com/threshold-poem/hello it will be `repoPath: '/hello'`

**Comment by Nicholas-Arthur-Cook** [comment]
Ahh thank you so much! That fixed it. I wonder how it was even working before haha. Thanks again!
